variables:
  CLI_VERSION: "0.1.2"

jobs:
- job: Check
  pool:
    vmImage: 'ubuntu-16.04'
  container:
    image: ubruhin/librepcb-cli-dev:$(CLI_VERSION)
    options: --entrypoint /bin/bash
  steps:
  - script: echo "Hello World"
#  - bash: librepcb-cli open-library --all --save .
#  - bash: git diff --exit-code  # fail if there are local changes
